# Ex2 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.

### Step 1. Import the necessary libraries

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/Euro_2012_stats_TEAM.csv).

In [ ]:
import pandas as pd

### Step 3. Assign it to a variable called euro12.

In [6]:
euro12 = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/Euro_2012_stats_TEAM.csv',index_col=0,low_memory=False)
euro12

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,13,65.1%,67,48,12,9,1,12,12,20
Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,...,20,74.1%,101,89,16,16,0,18,18,19
Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,...,6,66.7%,48,56,3,7,1,7,7,17
Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,...,10,71.5%,73,90,10,12,0,14,14,16
Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,...,17,65.4%,43,51,11,6,1,10,10,17
Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,...,10,77.0%,34,43,4,6,0,7,7,16
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,15,93.8%,102,83,19,11,0,17,17,18
Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,...,8,61.6%,35,51,7,7,0,9,9,18
Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,...,13,76.5%,48,31,4,5,0,9,9,18

### Step 4. Select only the Goal column.

In [11]:
euro12['Goals']

Team
Croatia                 4
Czech Republic          4
Denmark                 4
England                 5
France                  3
Germany                10
Greece                  5
Italy                   6
Netherlands             2
Poland                  2
Portugal                6
Republic of Ireland     1
Russia                  5
Spain                  12
Sweden                  5
Ukraine                 2
Name: Goals, dtype: int64

### Step 5. How many team participated in the Euro2012?

In [13]:
print(f"There are {euro12.shape[0]} teams which took part in Euro2012")

There are 16 teams which took part in Euro2012

### Step 6. What is the number of columns in the dataset?

In [14]:
print(f"There are: {euro12.shape[1]} columns")

There are: 34 columns

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [23]:
discipline = euro12[['Yellow Cards', 'Red Cards']]
discipline

                     Yellow Cards  Red Cards
Team
Croatia                         9          0
Czech Republic                  7          0
Denmark                         4          0
England                         5          0
France                          6          0
Germany                         4          0
Greece                          9          1
Italy                          16          0
Netherlands                     5          0
Poland                          7          1
Portugal                       12          0
Republic of Ireland             6          1
Russia                          6          0
Spain                          11          0
Sweden                          7          0
Ukraine                         5          0

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [30]:
#Sort the teams by Red Cards
df_redcards = euro12.sort_values('Red Cards')
df_redcards

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,...,20,74.1%,101,89,16,16,0,18,18,19
Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,...,8,61.6%,35,51,7,7,0,9,9,18
Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,...,10,71.5%,73,90,10,12,0,14,14,16
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,15,93.8%,102,83,19,11,0,17,17,18
Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,...,10,77.0%,34,43,4,6,0,7,7,16
Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,...,13,76.5%,48,31,4,5,0,9,9,18
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,13,65.1%,67,48,12,9,1,12,12,20
Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,...,17,65.4%,43,51,11,6,1,10,10,17
Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,...,6,66.7%,48,56,3,7,1,7,7,17

In [32]:
#Sort the teams by Yellow Cards
df_yellowcards = euro12.sort_values('Yellow Cards')
df_yellowcards

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,...,13,76.5%,48,31,4,5,0,9,9,18
Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,...,10,77.0%,34,43,4,6,0,7,7,16
Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,...,17,65.4%,43,51,11,6,1,10,10,17
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,...,8,61.6%,35,51,7,7,0,9,9,18
Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,...,6,66.7%,48,56,3,7,1,7,7,17
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,13,65.1%,67,48,12,9,1,12,12,20
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,15,93.8%,102,83,19,11,0,17,17,18
Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,...,10,71.5%,73,90,10,12,0,14,14,16
Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,...,20,74.1%,101,89,16,16,0,18,18,19

### Step 9. Calculate the mean Yellow Cards given per Team

In [34]:
print(f"The mean Yellow Cards given per Team is: {discipline['Yellow Cards'].mean()}")

The mean Yellow Cards given per Team is: 7.4375

### Step 10. Filter teams that scored more than 6 goals

In [36]:
euro12[euro12['Goals'] > 6]

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,15,93.8%,102,83,19,11,0,17,17,18

### Step 11. Select the teams that start with G

In [40]:
euro12[euro12.index.str.startswith('G')]

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,13,65.1%,67,48,12,9,1,12,12,20

### Step 12. Select the first 7 columns

In [42]:
euro12.head(6)

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,13,81.3%,41,62,2,9,0,9,9,16
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,10,66.7%,25,38,8,4,0,7,7,15
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,22,88.1%,43,45,6,5,0,11,11,16
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,10,62.6%,63,49,12,4,0,15,15,17

### Step 13. Select all columns except the last 3.

In [45]:
euro12.iloc[:, :-3]

,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,Headed goals,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
Team,,,,,,,,,,,,,,,,,,,,,
Croatia,4,13,12,51.9%,16.0%,32,0,0,0,2,...,0,10,3,13,81.3%,41,62,2,9,0
Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,0,...,1,10,6,9,60.1%,53,73,8,7,0
Denmark,4,10,10,50.0%,20.0%,27,1,0,0,3,...,1,10,5,10,66.7%,25,38,8,4,0
England,5,11,18,50.0%,17.2%,40,0,0,0,3,...,2,29,3,22,88.1%,43,45,6,5,0
France,3,22,24,37.9%,6.5%,65,1,0,0,0,...,1,7,5,6,54.6%,36,51,5,6,0
Germany,10,32,32,47.8%,15.6%,80,2,1,0,2,...,1,11,6,10,62.6%,63,49,12,4,0
Greece,5,8,18,30.7%,19.2%,32,1,1,1,0,...,1,23,7,13,65.1%,67,48,12,9,1
Italy,6,34,45,43.0%,7.5%,110,2,0,0,2,...,2,18,7,20,74.1%,101,89,16,16,0
Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,0,...,0,9,5,12,70.6%,35,30,3,5,0
Poland,2,15,23,39.4%,5.2%,48,0,0,0,1,...,0,8,3,6,66.7%,48,56,3,7,1
Portugal,6,22,42,34.3%,9.3%,82,6,0,0,2,...,2,11,4,10,71.5%,73,90,10,12,0
Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,1,...,0,23,9,17,65.4%,43,51,11,6,1
Russia,5,9,31,22.5%,12.5%,59,2,0,0,1,...,0,8,3,10,77.0%,34,43,4,6,0
Spain,12,42,33,55.9%,16.0%,100,0,1,0,2,...,5,8,1,15,93.8%,102,83,19,11,0
Sweden,5,17,19,47.2%,13.8%,39,3,0,0,1,...,1,12,5,8,61.6%,35,51,7,7,0
Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,2,...,0,4,4,13,76.5%,48,31,4,5,0

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [48]:
euro12.loc[['England', 'Italy', 'Russia'], 'Shooting Accuracy']

Team
England    50.0%
Italy      43.0%
Russia     22.5%
Name: Shooting Accuracy, dtype: object