# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [3]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/US_Baby_Names_right.csv',index_col=0,low_memory=False)
baby_names

              Id     Name  Year Gender State  Count
11349      11350     Emma  2004      F    AK     62
11350      11351  Madison  2004      F    AK     48
11351      11352   Hannah  2004      F    AK     46
11352      11353    Grace  2004      F    AK     44
11353      11354    Emily  2004      F    AK     41
...          ...      ...   ...    ...   ...    ...
5647421  5647422     Seth  2014      M    WY      5
5647422  5647423  Spencer  2014      M    WY      5
5647423  5647424     Tyce  2014      M    WY      5
5647424  5647425   Victor  2014      M    WY      5
5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 6 columns]

### Step 4. See the first 10 entries

In [4]:
baby_names.head(10)

          Id      Name  Year Gender State  Count
11349  11350      Emma  2004      F    AK     62
11350  11351   Madison  2004      F    AK     48
11351  11352    Hannah  2004      F    AK     46
11352  11353     Grace  2004      F    AK     44
11353  11354     Emily  2004      F    AK     41
11354  11355   Abigail  2004      F    AK     37
11355  11356    Olivia  2004      F    AK     33
11356  11357  Isabella  2004      F    AK     30
11357  11358    Alyssa  2004      F    AK     29
11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [5]:
df1 = baby_names.drop(columns=['Id'])
df1

            Name  Year Gender State  Count
11349       Emma  2004      F    AK     62
11350    Madison  2004      F    AK     48
11351     Hannah  2004      F    AK     46
11352      Grace  2004      F    AK     44
11353      Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
5647421     Seth  2014      M    WY      5
5647422  Spencer  2014      M    WY      5
5647423     Tyce  2014      M    WY      5
5647424   Victor  2014      M    WY      5
5647425   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [8]:
gender_counts = baby_names['Gender'].value_counts()
if(gender_counts['F'] > gender_counts['M']):
  print("There are more female name")
elif(gender_counts['F'] == gender_counts['M']):
  print("There are more male name")
else:
  print("Male and Female names are the same")

There are more female name

### Step 7. Group the dataset by name and assign to names

In [10]:
names = baby_names['Name']
names

11349         Emma
11350      Madison
11351       Hannah
11352        Grace
11353        Emily
            ...
5647421       Seth
5647422    Spencer
5647423       Tyce
5647424     Victor
5647425     Waylon
Name: Name, Length: 1016395, dtype: object

### Step 8. How many different names exist in the dataset?

In [12]:
counts = baby_names['Name'].nunique()
print(f"Co {counts} ten khac nhau")

Co 17632 ten khac nhau

### Step 9. What is the name with most occurrences?

In [14]:
print(baby_names.groupby('Name').Count.sum().idxmax())

Jacob

### Step 10. How many different names have the least occurrences?

In [17]:
print(f"The name which have the least occurrences is {baby_names.groupby('Name').Count.sum().idxmin()} - {baby_names.groupby('Name').Count.sum().min()} times")

The name which have the least occurrences is Aadarsh - 5 times

### Step 11. What is the median name occurrence?

In [26]:
df3 = baby_names.groupby('Name').Count.sum()
median = df3.median()
print(f"The median name occurrence is {median}")

The median name occurrence is 49.0

### Step 12. What is the standard deviation of names?

In [24]:
print(f"The standard deviation of name is: {df3.std()}")

The standard deviation of name is: 11006.069467891111

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
df3 = baby_names.groupby('Name').Count.sum()