# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [12]:
data = {'evolution':['Ivysaur','Charmeleon','Wartortle','Metapod'],
         'hp':[45,39,44,45],
         'name':['Bulbasaur','Charmander','Squirtle','Caterpie'],
         'pokedex':['yes','no','yes','no'],
         'type':['grass','fire','water','bug']}
df = pd.DataFrame(data)
df

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 3. Assign it to a variable called pokemon

In [11]:
pokemon = df
pokemon

    evolution  hp        name pokedex   type     place
0     Ivysaur  45   Bulbasaur     yes  grass     Hanoi
1  Charmeleon  39  Charmander      no   fire  Haiphong
2   Wartortle  44    Squirtle     yes  water       HCM
3     Metapod  45    Caterpie      no    bug    Danang

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [10]:
df2 = pd.DataFrame(pokemon,columns=['name','type','hp','evolution','pokedex'])
df

    evolution  hp        name pokedex   type     place
0     Ivysaur  45   Bulbasaur     yes  grass     Hanoi
1  Charmeleon  39  Charmander      no   fire  Haiphong
2   Wartortle  44    Squirtle     yes  water       HCM
3     Metapod  45    Caterpie      no    bug    Danang

### Step 5. Add another column called place, and insert what you have in mind.

In [9]:
pokemon['place']=['Hanoi','Haiphong','HCM','Danang']
pokemon

    evolution  hp        name pokedex   type     place
0     Ivysaur  45   Bulbasaur     yes  grass     Hanoi
1  Charmeleon  39  Charmander      no   fire  Haiphong
2   Wartortle  44    Squirtle     yes  water       HCM
3     Metapod  45    Caterpie      no    bug    Danang

### Step 6. Present the type of each column

In [13]:
pokemon.dtypes

evolution    object
hp            int64
name         object
pokedex      object
type         object
place        object
dtype: object

### BONUS: Create your own question and answer it.