# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/student-mat.csv',index_col=0,low_memory=False)
df

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
school,,,,,,,,,,,,,,,,,,,,,
GP,F,18,U,GT3,A,4,4,at_home,teacher,course,...,4,3,4,1,1,3,6,5,6,6
GP,F,17,U,GT3,T,1,1,at_home,other,course,...,5,3,3,1,1,3,4,5,5,6
GP,F,15,U,LE3,T,1,1,at_home,other,other,...,4,3,2,2,3,3,10,7,8,10
GP,F,15,U,GT3,T,4,2,health,services,home,...,3,2,2,1,1,5,2,15,14,15
GP,F,16,U,GT3,T,3,3,other,other,home,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MS,M,20,U,LE3,A,2,2,services,services,course,...,5,5,4,4,5,4,11,9,9,9
MS,M,17,U,LE3,T,3,1,services,services,course,...,2,4,5,3,4,2,3,14,16,16
MS,M,21,R,GT3,T,1,1,other,other,course,...,5,5,3,3,3,3,3,10,8,7
MS,M,18,R,LE3,T,3,2,services,other,course,...,4,4,1,3,4,5,0,11,12,10
MS,M,19,U,LE3,T,1,1,other,at_home,course,...,3,2,3,3,3,5,5,8,9,9

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [13]:
stud_alcoh = df.loc[:,:'guardian']
stud_alcoh

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
school,,,,,,,,,,,
GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
GP,F,17,U,GT3,T,1,1,at_home,other,course,father
GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
GP,F,15,U,GT3,T,4,2,health,services,home,mother
GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...
MS,M,20,U,LE3,A,2,2,services,services,course,other
MS,M,17,U,LE3,T,3,1,services,services,course,mother
MS,M,21,R,GT3,T,1,1,other,other,course,other
MS,M,18,R,LE3,T,3,2,services,other,course,mother
MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [14]:
capitalize = lambda x:x.capitalize()
capitalize

### Step 6. Capitalize both Mjob and Fjob

In [15]:
stud_alcoh['Mjob'] = stud_alcoh['Mjob'].apply(capitalize)
stud_alcoh['Fjob'] = stud_alcoh['Fjob'].apply(capitalize)
stud_alcoh.head()

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
school,,,,,,,,,,,
GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,mother
GP,F,17,U,GT3,T,1,1,At_home,Other,course,father
GP,F,15,U,LE3,T,1,1,At_home,Other,other,mother
GP,F,15,U,GT3,T,4,2,Health,Services,home,mother
GP,F,16,U,GT3,T,3,3,Other,Other,home,father

### Step 7. Print the last elements of the data set.

In [18]:
stud_alcoh.tail(1)

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
school,,,,,,,,,,,
MS,M,19,U,LE3,T,1,1,Other,At_home,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [19]:
df['Mjob'] = df['Mjob'].apply(capitalize)
df['Fjob'] = df['Fjob'].apply(capitalize)
df.head()

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
school,,,,,,,,,,,,,,,,,,,,,
GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,...,4,3,4,1,1,3,6,5,6,6
GP,F,17,U,GT3,T,1,1,At_home,Other,course,...,5,3,3,1,1,3,4,5,5,6
GP,F,15,U,LE3,T,1,1,At_home,Other,other,...,4,3,2,2,3,3,10,7,8,10
GP,F,15,U,GT3,T,4,2,Health,Services,home,...,3,2,2,1,1,5,2,15,14,15
GP,F,16,U,GT3,T,3,3,Other,Other,home,...,4,3,2,1,2,5,4,6,10,10

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [20]:
def majority(age):
    return age > 17

In [21]:
df['legal_drinker'] = df['age'].apply(majority)
display(df.head())

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
school,,,,,,,,,,,,,,,,,,,,,
GP,F,18,U,GT3,A,4,4,At_home,Teacher,course,...,3,4,1,1,3,6,5,6,6,True
GP,F,17,U,GT3,T,1,1,At_home,Other,course,...,3,3,1,1,3,4,5,5,6,False
GP,F,15,U,LE3,T,1,1,At_home,Other,other,...,3,2,2,3,3,10,7,8,10,False
GP,F,15,U,GT3,T,4,2,Health,Services,home,...,2,2,1,1,5,2,15,14,15,False
GP,F,16,U,GT3,T,3,3,Other,Other,home,...,3,2,1,2,5,4,6,10,10,False

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [22]:
for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        df[col] = df[col] * 10
display(df.head())

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,legal_drinker
school,,,,,,,,,,,,,,,,,,,,,
GP,F,180,U,GT3,A,40,40,At_home,Teacher,course,...,30,40,10,10,30,60,50,60,60,True
GP,F,170,U,GT3,T,10,10,At_home,Other,course,...,30,30,10,10,30,40,50,50,60,False
GP,F,150,U,LE3,T,10,10,At_home,Other,other,...,30,20,20,30,30,100,70,80,100,False
GP,F,150,U,GT3,T,40,20,Health,Services,home,...,20,20,10,10,50,20,150,140,150,False
GP,F,160,U,GT3,T,30,30,Other,Other,home,...,30,20,10,20,50,40,60,100,100,False