# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
s1 = pd.Series(np.random.randint(1, 5, size = 100))
s2 = pd.Series(np.random.randint(1, 4, size = 100))
s3 = pd.Series(np.random.randint(10000, 30001, size = 100))
print(s1.head(),s2.head(),s3.head())

0    1
1    4
2    3
3    1
4    1
dtype: int64 0    2
1    2
2    1
3    2
4    2
dtype: int64 0    21076
1    16917
2    26321
3    13367
4    16205
dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [4]:
df = pd.concat([s1,s2,s3],axis=1)
df

    0  1      2
0   1  2  21076
1   4  2  16917
2   3  1  26321
3   1  2  13367
4   1  2  16205
.. .. ..    ...
95  4  1  24418
96  3  2  16060
97  2  3  12145
98  2  1  24773
99  3  3  19404

[100 rows x 3 columns]

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [10]:
df.columns = ['bedrs', 'bathrs', 'price_sqr_meter']
df

    bedrs  bathrs  price_sqr_meter
0       1       2            21076
1       4       2            16917
2       3       1            26321
3       1       2            13367
4       1       2            16205
..    ...     ...              ...
95      4       1            24418
96      3       2            16060
97      2       3            12145
98      2       1            24773
99      3       3            19404

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [11]:
bigcolumn = pd.concat([s1,s2,s3],axis=0)
bigcolumn = pd.DataFrame(bigcolumn)
bigcolumn

        0
0       1
1       4
2       3
3       1
4       1
..    ...
95  24418
96  16060
97  12145
98  24773
99  19404

[300 rows x 1 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [12]:
print(len(bigcolumn))
print(bigcolumn.index)

300
Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [13]:
bigcolumn.reset_index(drop=True,inplace=True)
bigcolumn

         0
0        1
1        4
2        3
3        1
4        1
..     ...
295  24418
296  16060
297  12145
298  24773
299  19404

[300 rows x 1 columns]