# Exercise 1

### Step 1. Go to https://www.kaggle.com/openfoodfacts/world-food-facts/data

### Step 2. Download the dataset to your computer and unzip it.

In [9]:
import pandas as pd

### Step 3. Use the tsv file and assign it to a dataframe called food

In [21]:
food = pd.read_csv('./sample_data/openfoodfacts.tsv',sep='\t',low_memory=False)
food

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23725,28189616577,http://world-en.openfoodfacts.org/product/0028...,usda-ndb-import,1489062838,2017-03-09T12:33:58Z,1489062838,2017-03-09T12:33:58Z,Red Enchilada Sauce,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN
23726,28189620604,http://world-en.openfoodfacts.org/product/0028...,usda-ndb-import,1489062265,2017-03-09T12:24:25Z,1489062266,2017-03-09T12:24:26Z,Red Enchilada Sauce,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,NaN,NaN
23727,28189628709,http://world-en.openfoodfacts.org/product/0028...,usda-ndb-import,1489053183,2017-03-09T09:53:03Z,1489053183,2017-03-09T09:53:03Z,Nacho Sliced Jalapenos,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,NaN,NaN
23728,28189628723,http://world-en.openfoodfacts.org/product/0028...,usda-ndb-import,1489094266,2017-03-09T21:17:46Z,1489094266,2017-03-09T21:17:46Z,Jalapeno Nacho Slices,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN
23729,28189711722,http://world-en.openfoodfacts.org/product/0028...,usda-ndb-import,1489062824,2017-03-09T12:33:44Z,1489062824,2017-03-09T12:33:44Z,Chopped Green Chiles,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 4. See the first 5 entries

In [22]:
food.head(5)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,3087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,4559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,16087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,16094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Step 5. What is the number of observations in the dataset?

In [33]:
print(f"The table includes : {food.shape[0]} rows and {food.shape[1]} columns")

The table includes : 23730 rows and 163 columns

### Step 6. What is the number of columns in the dataset?

In [34]:
print(f"There are {food.shape[1]} columns")

There are 163 columns

### Step 7. Print the name of all the columns.

In [41]:
food.axes[1]

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

### Step 8. What is the name of 105th column?

In [48]:
food.columns[104]

'-glucose_100g'

### Step 9. What is the type of the observations of the 105th column?

In [49]:
print(food.dtypes[104])

float64

/tmp/ipykernel_2107/3452635071.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(food.dtypes[104])

### Step 10. How is the dataset indexed?

In [50]:
food.index

RangeIndex(start=0, stop=23730, step=1)

### Step 11. What is the product name of the 19th observation?

In [51]:
print(food.iloc[18]['product_name'])

Lotus Organic Brown Jasmine Rice